import type { Metadata } from "next";
import { geistMono, geistSans } from "@/app/ui/fontui";
import "./globals.css";
import StoreProvider from "./store/StoreProvider";
import TopNavBar from "./ui/navbar/topnav";
import Footer from "./ui/footer/foot";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <div>
          {/* NavBar */}
          <TopNavBar />
        </div>
        <StoreProvider>
          <div className="flex-grow">{children}</div>
        </StoreProvider>
        <div>
          {/* Footer */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
